include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    prefer_is_empty: true
    prefer_is_not_empty: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
