name: witt
repository: https://github.com/webblabsorg/witt

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze --fatal-infos
    description: Run dart analyze in all packages.

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages.
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages.

  build_runner:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages.
    packageFilters:
      dependsOn: build_runner

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages.
